#: kivy 1.0.9

<ccGame>:    
    canvas:

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size
            source: 'background.png'
    Label:
        font_size: 50
        center_x: root.width * 0.5
        center_y: root.height * 0.5
        text: "Hello World!"

